openapi: 3.0.2
info:
  contact:
    email: cloudharness@metacell.us
  description: Accounts rest api
  license:
    name: UNLICENSED
  title: accounts_api
  version: 0.1.0
servers:
- url: /api
tags:
- description: ""
  name: infrastructure
- description: ""
  name: users
paths:
  /groups/{groupname}/:
    get:
      operationId: get_group
      parameters:
      - explode: false
        in: path
        name: groupname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
          description: Get a user's public information
      tags:
      - groups
      x-openapi-router-controller: accounts_api.controllers.groups_controller
    put:
      operationId: update_group
      parameters:
      - explode: false
        in: path
        name: groupname
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: The user as just saved
      security:
      - bearerAuth: []
      tags:
      - groups
      x-openapi-router-controller: accounts_api.controllers.groups_controller
  /groups/{groupname}/users:
    get:
      operationId: get_group_users
      parameters:
      - explode: false
        in: path
        name: groupname
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: Get a user's public information
      tags:
      - groups
      x-openapi-router-controller: accounts_api.controllers.groups_controller
  /live:
    get:
      operationId: live
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Healthy
        "500":
          description: Application is not healthy
      summary: Test if application is healthy
      tags:
      - infrastructure
      x-openapi-router-controller: accounts_api.controllers.infrastructure_controller
  /ready:
    get:
      operationId: ready
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Ready
        "500":
          description: Application is not ready yet
      summary: Test if application is ready to take requests
      tags:
      - infrastructure
      x-openapi-router-controller: accounts_api.controllers.infrastructure_controller
  /users:
    get:
      operationId: get_users
      parameters:
      - description: "free-text filter on username, first/last name or email"
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      - description: 1-based page number
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: page size
        explode: true
        in: query
        name: per_page
        required: false
        schema:
          default: 20
          minimum: 1
          type: integer
        style: form
      - description: field to sort by
        explode: true
        in: query
        name: sort_by
        required: false
        schema:
          default: registration_date
          enum:
          - registration_date
          - username
          - name
          - first_name
          - last_name
          - workspaces
          - repositories
          type: string
        style: form
      - description: sort direction
        explode: true
        in: query
        name: sort_order
        required: false
        schema:
          default: desc
          enum:
          - asc
          - desc
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/get_users_200_response'
          description: Get list of users
      security:
      - bearerAuth: []
      summary: Get list of users based on query
      tags:
      - users
      x-openapi-router-controller: accounts_api.controllers.users_controller
  /users/{userid}:
    get:
      operationId: get_user
      parameters:
      - description: user id
        explode: false
        in: path
        name: userid
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Get a user's public information
      tags:
      - users
      x-openapi-router-controller: accounts_api.controllers.users_controller
    put:
      operationId: update_user
      parameters:
      - description: user id
        explode: false
        in: path
        name: userid
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: The user as just saved
      security:
      - bearerAuth: []
      tags:
      - users
      x-openapi-router-controller: accounts_api.controllers.users_controller
components:
  schemas:
    Valid:
      properties:
        response:
          type: string
      type: object
    Url:
      description: ""
      title: image
      type: string
    Profiles:
      additionalProperties: true
      description: ""
      title: quotas
      type: object
    User:
      additionalProperties: true
      description: Keycloak User
      example:
        firstName: firstName
        lastName: lastName
        website: website
        quotas:
          key: ""
        profiles:
          key: ""
        registrationDate: 2000-01-23
        groups:
        - groups
        - groups
        id: id
        avatar: avatar
        email: email
        username: username
      properties:
        id:
          description: user id
          type: string
        username:
          description: Username of the keycloak user
          type: string
        email:
          description: Email address of the keycloak user
          type: string
        firstName:
          description: First Name of the keycloak user
          type: string
        lastName:
          description: Last Name of the keycloak user
          type: string
        groups:
          description: ""
          items:
            type: string
          readOnly: true
          type: array
        profiles:
          additionalProperties: true
          description: ""
          title: quotas
          type: object
        registrationDate:
          description: ""
          format: date
          type: string
        avatar:
          description: ""
          title: image
          type: string
        website:
          description: ""
          title: image
          type: string
        quotas:
          additionalProperties: true
          description: ""
          title: quotas
          type: object
      title: User
      type: object
    Group:
      description: ""
      example:
        image: image
        quotas:
          key: ""
        keywords:
        - keywords
        - keywords
        name: name
        description: ""
        links:
          key: ""
        email: email
      properties:
        quotas:
          additionalProperties: true
          description: ""
          title: quotas
          type: object
        name:
          description: ""
          title: name
          type: string
        description:
          description: ""
          title: description
        links:
          additionalProperties: true
          description: ""
          title: quotas
          type: object
        keywords:
          description: ""
          items:
            type: string
          title: keywords
          type: array
        image:
          description: ""
          title: image
          type: string
        email:
          description: ""
          title: email
          type: string
      required:
      - name
      title: Group
      type: object
    get_users_200_response_pagination:
      example:
        per_page: 1
        total: 0
        number_of_pages: 5
        current_page: 6
      properties:
        total:
          title: total
          type: integer
        current_page:
          title: current_page
          type: integer
        per_page:
          title: per_page
          type: integer
        number_of_pages:
          title: number_of_pages
          type: integer
      title: get_users_200_response_pagination
      type: object
    get_users_200_response:
      example:
        pagination:
          per_page: 1
          total: 0
          number_of_pages: 5
          current_page: 6
        users:
        - firstName: firstName
          lastName: lastName
          website: website
          quotas:
            key: ""
          profiles:
            key: ""
          registrationDate: 2000-01-23
          groups:
          - groups
          - groups
          id: id
          avatar: avatar
          email: email
          username: username
        - firstName: firstName
          lastName: lastName
          website: website
          quotas:
            key: ""
          profiles:
            key: ""
          registrationDate: 2000-01-23
          groups:
          - groups
          - groups
          id: id
          avatar: avatar
          email: email
          username: username
      properties:
        users:
          items:
            $ref: '#/components/schemas/User'
          title: users
          type: array
        pagination:
          $ref: '#/components/schemas/get_users_200_response_pagination'
        counts:
          additionalProperties:
            properties:
              workspaces:
                type: integer
              repositories:
                type: integer
            type: object
          description: "Workspace/repository counts for the returned users, keyed\
            \ by user id. Omitted entries mean the counts are unknown."
          title: counts
          type: object
      title: get_users_200_response
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
      x-bearerInfoFunc: cloudharness.auth.decode_token
